# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published
# by the Free Software Foundation.#
# Makefile for the Nintendo 64 stuff
#
# Copyright (C) 2016 Murachue <murachue@gmail.com>

#obj-y := prom.o of.o reset.o clk.o irq.o timer.o

obj-$(CONFIG_NINTENDO64) += n64.o

#obj-$(CONFIG_EARLY_PRINTK) += early_printk.o

#obj-$(CONFIG_DEBUG_FS) += bootrom.o
